# Model type
model: dgcn_agg

# Model options
node_feat_dim: 4
layer_1_dim: 16
layer_2_dim: 16
temporal_in_dim: 16
temporal_out_dim: 16
temporal_num_layers: 2
temporal_layer: lstm

clf_in_dim: 16
fc_1_dim: 16
fc_2_dim: 16
out_dim: 3

dropout: 0.5

# training args
optimizer: sgd
optim_args:
  lr: 0.01
  momentum: 0.9
skipfeats: false
epochs: 10
returns_threshold: 0.01
batchsize: 2

# dataset args
dataset: main
seq_length: 30
predict_periods: 1
features:
  - adjVolume
  - adjHigh
  - adjLow

# misc
timeout: 10000
size: small
plot: false
file: evolvegcn.out