# Model type
model: dgcn
adj: false
adj2: true
k: false
format: edge_index

# Model options
node_feat_dim: 4
layer_1_dim: 512
layer_2_dim: 512
lstm_dim: 256

num_layers: 2
fc_1_dim: 128
fc_2_dim: 3
dropout: 0.5

# training args
optimizer: adam
optim_args:
  lr: 0.001
  weight_decay: 0.1
skipfeats: false
epochs: 10
seq_length: 30
predict_periods: 1
returns_threshold: 0.01
batchsize: null
features:
  - adjVolume
  - adjHigh
  - adjLow


# misc
timeout: 10000
dataset: small
plot: false
file: evolvegcn.out