# Model type
model: dgcn2
conv_first: false

# Model options
node_feat_dim: 4

temporal_layer: lstm
temporal_in_dim: 4
temporal_out_dim: 16
temporal_num_layers: 2

layer_1_dim: 16
layer_2_dim: 16

clf_in_dim: 16
fc_1_dim: 16
fc_2_dim: 16
out_dim: 3
dropout: 0.2

# training args
optimizer: sgd
optim_args:
  lr: 0.01
  momentum: 0.9
skipfeats: false
epochs: 10
returns_threshold: 0.01
batchsize: 2
edgetypes:
  - 0

# dataset args
dataset: main
seq_length: 30
predict_periods: 3
features:
  - adjVolume
  - adjHigh
  - adjLow

# misc
timeout: 10000
size: small
plot: false
file: evolvegcn.out