# Model type
model: evolve

# Model options
node_feat_dim: 4
layer_1_dim: 16
layer_2_dim: 16
ratio: 0.5
num_layers: 1

# training args
optimizer: sgd
optim_args:
  lr: 0.01
  momentum: 0.9
skipfeats: false
epochs: 10
returns_threshold: 0.01
batchsize: 2
edgetype: 2

# dataset args
dataset: main
seq_length: 30
predict_periods: 1
features:
  - adjVolume
  - adjHigh
  - adjLow

# misc
timeout: 10000
size: small
plot: false
file: evolvegcn.out