# Model type
model: dgcn2
conv_first: false

# Model options
node_feat_dim: 6

temporal_layer: lstm
temporal_in_dim: 6
temporal_num_layers: 2
temporal_out_dim: 128

layer_1_dim: 128
layer_2_dim: 128

clf_in_dim: 128
fc_1_dim: 64
fc_2_dim: 32
out_dim: 3

dropout: 0.5

# training args
optimizer: sgd
optim_args:
  lr: 0.001
  momentum: 0.9
skipfeats: false
epochs: 10
returns_threshold: 0.008
batchsize: 20
edgetypes:
  - 0

# dataset args
dataset: main
seq_length: 50
predict_periods: 3
features:
  - adjVolume
  - 5-day
  - 10-day
  - 20-day
  - 30-day

# misc
timeout: 10000
size: small
plot: false
file: dgcn2_cnn.out