# Model type
model: lstm
adj: false
adj2: false

# Model options
lstm_input_size: 2
layer_2_dim: 200
num_layers: 2
fc_1_dim: 100
fc_2_dim: 3
dropout: 0.5

# training args
optimizer: sgd
optim_args:
  lr: 0.001
  momentum: 0.9
skipfeats: false
epochs: 10
seq_length: 30
predict_periods: 1
returns_threshold: 0.01
features:
  - adjVolume


# misc
timeout: 10000
dataset: small
plot: false
file: evolvegcn.out